fixtures:
  repositories:
    redis: git://github.com/thomasvandoren/puppet-redis.git
    git:  git://github.com/puppetlabs/puppetlabs-git.git
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vscrepo.git
  symlinks:
    "redis_live": "#{source_dir}"
