name         'thomasvandoren-redis_live'
version      '0.0.1'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/thomasvandoren/puppet-RedisLive'
dependency   'puppetlabs/git'
dependency   'puppetlabs/vcsrepo'
dependency   'thomasvandoren/redis'
